### ISSUE TITLE
private key

### ISSUE THREAD

**Issue by bernhardIII** [vechain/thor-sync#2]
Hey programer, AsbertMa, after open a new account with Sync 0.6.1 i wanted to export my private key. but it does not work to store the txt-file. how does it work  or what can i do? thanx a lot and great work since i do not want to get a mobile app for my vtho. bernhard
macos 10.12.
chrome Version 67.0.3396.99

**Comment by AsbertMa** [comment]
Hi, bernhard, i got the point.
Solutions:
1. Next release.
2. Run a piece of codes. (Not friendly for normal user but developers, send email to you)

**Comment by AsbertMa** [comment]
@bernhardIII Update to latest release.

**Comment by ghost** [comment]
Hello @AsbertMa , is it safe for me to store all my VET on the sync account? Assuming I protect my private keys and the phase correctly? Because, the sync/wallet is a online wallet, correct? I only need to store my private keys and the phase, I guess.

**Comment by XJWX89** [comment]
Hello @Kirasaitru , Sync uses the same storage method for keysotre file as parity and go ethereum

**Comment by AsbertMa** [comment]
Hello @Kirasaitru , i got you question last night, but didn't reply immediately. I need hours to think how to reply.
There are somethings i want you know.
1. There is NO absolute security, that's depends on things. 
2. **Protect you private keys and phase**. (Right)
3. Keystores are stored on your computer and could get the files directly. **Keystore with the right password could export the private key.** So protect your computer and care about the operations.
4. Sync uses the same storage method for keysotre file as parity and go ethereum.

We will do the wiki to improve user be conscious of security.
