### ISSUE TITLE
No Testnet after Upgrade to 0.6.5

### ISSUE THREAD

**Issue by mirei83** [vechain/thor-sync#3]
After upgrading sync from 0.6.2 to 0.6.5 I cant sync with Testnet anymore. I deleted the DB instance in C:\Users\USER\AppData\Roaming\org.vechain.thor\instance-7f466536b20bb127; deinstalled and reinstalled 0.6.5. Syncing always gives me "error". After downgrade to 0.6.2 everything is fine again.

But the software keeps updating to 0.6.5...

**Comment by AsbertMa** [comment]
@mirei83 There is a workaround way, Start the test net manually. By this way, the switch net work will be unuseful. 

windows terminal
C:\Users\USER\AppData\Roaming\org.vechain.ua\thor.exe --network test -api-cors *

**Comment by XJWX89** [comment]
@mirei83  please let us know if the issue still occurs in 0.6.6 version

**Comment by mirei83** [comment]
After upgrading to 0.6.6 the problem is resolved for me. Thanks for the quick response.
But I definetly dont like the "force auto update" option. ;)
