### ISSUE TITLE
Choose network type before initial sync. 

### ISSUE THREAD

**Issue by jiayuzhou** [vechain/thor-sync#6]
When starting the Sync application we are forced to sync mainnet data.  However, for many developers, we are (initially) interested in testnet data only. I would suggest a network selector before starting syncing mainnet data automatically.

**Comment by qianbin** [comment]
There's a workaround:
Start a standalone thor node connect to dev net, then open Sync app.

**Comment by jiayuzhou** [comment]
Good to know. It will be great to add this to the README file.
