### ISSUE TITLE
Wallet Syncing and Opening - Will not open and says network error. Help!

### ISSUE THREAD

**Issue by resurglee1980** [vechain/thor-sync#7]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by XJWX89** [comment]
@resurglee1980  please provide more details, such as "sync version ", "OS version "....etc

**Comment by resurglee1980** [comment]
How do I find out "sync version" etc.? It is for Windows laptop. Do I go to "Toggle Development Tools" in the 'Edit' tab? I only have the 'Edit' tab as an option to go to. Thank you!

**Comment by libotony** [comment]
Go to 'Help' -> 'About Sync'

**Comment by resurglee1980** [comment]
Like I said above, there is only one option for me to click on ('Edit') There is no HELP option. I only have the option to click on an 'Edit' tab. That is it. When I click on the 'Edit' tab it only shows these options: undo, redo, cut, copy, paste, paste and match style, delete, select all, toggle developer tools. The wallet shows the icon of a house (which I cannot click on) on the left side and on the right side of the wallet, it shows 'Error Best Block:' which you also cannot click on. Other than that I can click to minimize, maximize or close. Nothing else is clickable. Does this make sense?

**Comment by mark54mco** [comment]
I have a similar problem:
When I click my Sync Icon it opens Sync, as usual, but after making sync progress from about 75% to about 91%, it stopped and is frozen on Best Block 10,075,613, where it has been for several reboots and 5 days.
I expect it to complete the sync and open my wallet at 100%
I am running Mojave Version 10.14.1
Browser: Safari Version 12.0.1 
There is nothing in the window that can be successfully clicked
I have Version 0.6.7 (0.6.7) of Sync.  When I click "Check Update" in the menu it says, "There are no updates available."

**Comment by XJWX89** [comment]
hello @resurglee1980  , whats the windows version on you laptop(win10?)?  could you try download the [0.6.9](https://github.com/vechain/thor-sync/releases/download/v0.6.9/sync-setup-0.6.9.exe) and re-install?

**Comment by mark54mco** [comment]
I have the latest upgrade of Mac — Mojave

**Comment by resurglee1980** [comment]
Yes, I have Windows 10 and it's a Laptop. I have re-installed 0.6.9 but it does the exact same thing. As soon as I open it jumps to 'Error: Network Error'. And in the top right corner, it says 'Error: Best Block'. It never syncs and does not give me any option to GET INTO my wallet to remove the funds.

**Comment by XJWX89** [comment]
Hi @resurglee1980 ,Please follow below step and provide us some log 
1. open  command line (Press Windows+R to open “Run” box. Type “cmd” and then click “OK” to open a regular Command Prompt.)
2. input `cd %APPDATA%\org.vechain.ua/`
3. input ` thor.exe --network main`
4. wait for a bit and provide  us the information which shown on your command line

Moreover, you can find your keystore at `%APPDATA%\org.vechain.ua/keystore/`.

**Comment by resurglee1980** [comment]
Hi and Happy New Year! So I did what you suggested and here is what I got:

Microsoft Windows [Version 10.0.17134.472]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\resur>cd %APPDATA%\org.vechain.ua/

C:\Users\resur\AppData\Roaming\org.vechain.ua>thor.exe --network main
Fatal: open log database [C:\Users\resur\AppData\Roaming\org.vechain.thor\instance-39627e6be7ec1b4a\logs.db]: database disk image is malformed

**Comment by libotony** [comment]
@resurglee1980 Please close sync and remove the data dir from your disk `C:\Users\resur\AppData\Roaming\org.vechain.thor\instance-39627e6be7ec1b4a\`  then try again

**Comment by mark54mco** [comment]
Thank you for your help.  Looks like I got it!
